export const blogList = [{
    id: 1,
    title: '7 CSS tools you should be using ',
    category: 'development',
    subCategory: ['frontend', 'ui/ux', 'design'],
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'Navdeep Singh',
    authorAvatar: '/Assets/images/author.png',
    createdAt: 'June 03, 2021',
    cover: '/Assets/images/bird.jpg',
},
{
    id: 2,
    title: 'Milan Places That Highlight The City',
    category: 'travel',
    subCategory: ['vacation', 'holidays', 'sight seeing'],
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'Navdeep Singh',
    authorAvatar: '/Assets/images/author.png',
    createdAt: 'June 03, 2021',
    cover: '/Assets/images/flower.jpg',
},
{
    id: 3,
    title: 'Online Shopping - An Alternative to Shopping in the Mall',
    category: 'shopping',
    subCategory: ['e-commerce store', 'clothing', 'shopping store'],
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'Navdeep Singh',
    authorAvatar: '/Assets/images/author.png',
    createdAt: 'June 03, 2021',
    cover: '/Assets/images/georgia.jpg',
},
{
    id: 4,
    title: 'Adventure Sports for the Adrenaline Junkie',
    category: 'adventure',
    subCategory: ['adrenaline', 'stay-fit', 'lifestyle'],
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'Navdeep Singh',
    authorAvatar: '/Assets/images/author.png',
    createdAt: 'June 03, 2021',
    cover: '/Assets/images/mountains.jpg',
},
{
    id: 5,
    title: 'Loaded BBQ Baked Potatoes',
    category: 'cooking',
    subCategory: ['bbq', 'food', 'lifestyle'],
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'Navdeep Singh',
    authorAvatar: '/Assets/images/author.png',
    createdAt: 'June 03, 2021',
    cover: '/Assets/images/pine-needles.jpg',
},
{
    id: 6,
    title: 'Beyond the Beach',
    category: 'travel',
    subCategory: ['beaches', 'sea', 'holidays'],
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'Navdeep Singh',
    authorAvatar: '/Assets/images/author.png',
    createdAt: 'June 03, 2021',
    cover: '/Assets/images/squirrel.jpg',
},
{
    id: 7,
    title: 'Art & Perception',
    category: 'art',
    subCategory: ['skill', 'design', 'passion'],
    description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'Navdeep Singh',
    authorAvatar: '/Assets/images/author.png',
    createdAt: 'June 03, 2021',
    cover: '/Assets/images/lake.jpg',
},
];